#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-blockenspiel
Version  : 0.4.5
Release  : 3
URL      : https://rubygems.org/downloads/blockenspiel-0.4.5.gem
Source0  : https://rubygems.org/downloads/blockenspiel-0.4.5.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
== Blockenspiel
Blockenspiel is a helper library designed to make it easy to implement DSL
blocks. It is designed to be comprehensive and robust, supporting most common
usage patterns, and working correctly in the presence of nested blocks and
multithreading.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n blockenspiel-0.4.5
gem spec %{SOURCE0} -l --ruby > rubygem-blockenspiel.gemspec

%build
gem build rubygem-blockenspiel.gemspec

%install
gem_dir=$(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .${gem_dir} \
--bindir .%{_bindir} \
blockenspiel-0.4.5.gem

mkdir -p %{buildroot}${gem_dir}
cp -pa .${gem_dir}/* \
%{buildroot}${gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/blockenspiel-0.4.5.gem
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/BlockParameterError/cdesc-BlockParameterError.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/BlockenspielError/cdesc-BlockenspielError.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/Builder/Target/cdesc-Target.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/Builder/add_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/Builder/cdesc-Builder.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/DSL/cdesc-DSL.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/DSLMissingError/cdesc-DSLMissingError.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/DSLSetupMethods/cdesc-DSLSetupMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/DSLSetupMethods/dsl_attr_accessor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/DSLSetupMethods/dsl_attr_writer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/DSLSetupMethods/dsl_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/DSLSetupMethods/dsl_methods-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/DSLSetupMethods/klass_/cdesc-klass_.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/ProxyDelegator/cdesc-ProxyDelegator.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/Unmixer/cdesc-Unmixer.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/cdesc-Blockenspiel.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/Blockenspiel/invoke-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/ext/unmixer_mri/page-Makefile.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/page-Blockenspiel_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/page-History_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/page-ImplementingDSLblocks_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/blockenspiel-0.4.5/ri/unknown/cdesc-unknown.ri
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/blockenspiel-0.4.5/blockenspiel/unmixer_mri.so
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/blockenspiel-0.4.5/gem.build_complete
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/blockenspiel-0.4.5/gem_make.out
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/blockenspiel-0.4.5/mkmf.log
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/Blockenspiel.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/History.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/ImplementingDSLblocks.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/Version
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/ext/unmixer_mri/.RUBYARCHDIR.-.blockenspiel.time
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/ext/unmixer_mri/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/ext/unmixer_mri/extconf.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/ext/unmixer_mri/unmixer_mri.c
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/ext/unmixer_mri/unmixer_mri.o
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/ext/unmixer_mri/unmixer_mri.so
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/lib/blockenspiel.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/lib/blockenspiel/builder.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/lib/blockenspiel/dsl_setup.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/lib/blockenspiel/errors.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/lib/blockenspiel/impl.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/lib/blockenspiel/unmixer_mri.so
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/lib/blockenspiel/unmixer_rubinius.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/lib/blockenspiel/unmixer_unimplemented.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/lib/blockenspiel/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/lib/blockenspiel/versionomy.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/lib/blockenspiel_unmixer_jruby.jar
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/test/files/file1.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/test/tc_basic.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/test/tc_behaviors.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/test/tc_dsl_attrs.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/test/tc_dsl_methods.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/test/tc_dynamic.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/test/tc_embedded_block.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/test/tc_mixins.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/test/tc_modules.rb
/usr/lib64/ruby/gems/2.2.0/gems/blockenspiel-0.4.5/test/tc_version.rb
/usr/lib64/ruby/gems/2.2.0/specifications/blockenspiel-0.4.5.gemspec
